flightctl/flightctl

- README.md
- deploy/podman/compose.yaml
Without this you can't locally deploy on an arm64 mac book. The caveat is that this image is behind login and you will need to run:
```
podman login registry.redhat.io
```
> Allow using a multi-arch image for postgresql

- cmd/flightctl-server/main.go
- deploy/podman/config.yaml
- internal/config/config.go
Support altNames in server cert:
```
X509v3 Subject Alternative Name:
DNS:my-host.abc.com, DNS:localhost
```
> Support altnames in flightctl-server config

- .github/workflows/pr-smoke-testing.yaml
Reverts flightctl/flightctl#29
This didn't really help as the package doesn't seem to be available in their repository versions anymore.
We can only wait to get an updated conmon or go back to podman3
> Revert "Fix conmon issue with 2.1.9 on CI"

- cmd/devicesimulator/main.go
- cmd/flightctl-agent/main.go
- internal/agent/agent.go
- internal/store/device.go
- internal/store/enrollmentrequest.go
- internal/store/fleet.go
- internal/store/repository.go
- pkg/log/log.go
- pkg/reqid/reqid.go
To monitor operations between agent and the service it require to keep using the same request-id on each interaction.
Added a reqid package to have a standard request id format and a way to get a new request id when needed.
Sequential request id will better to understand the flow of the interaction
Instead of passing the logger to each function device logger is updated on each interaction with the request id field.
In the future if there will be async operations on the agent it will require to pass the logger with the relevant request id to the async part in order to trace the operations
I decided not to use the context to keep the request id because the way `WithValue` function is implemented, it will add additional context each time with value is called in the long run it will create a …
> Add logrus usage to agent

- internal/monitors/device-updater/device_updater.go
- internal/monitors/device-updater/device_updater_test.go
- internal/monitors/repotester/repotester.go
- internal/monitors/repotester/repotester_test.go
- internal/server/server.go
- internal/service/device.go
- internal/service/enrollmentrequest.go
- internal/service/fleet.go
- internal/service/handler.go
- internal/service/repository.go
- internal/service/resourcesync.go
- internal/store/device.go
- internal/store/enrollmentrequest.go
- internal/store/fleet.go
- internal/store/repository.go
- internal/store/resourcesync.go
- internal/store/store.go
While `oapi-codegen` generates its interfaces with the `Interface` suffix this pattern isn't followed in idiomatic go. This PR renames all non codegen interfaces removing this `Interface` suffix which can be assumed by its type.
> internal: remove Interface from non generated interface names

- .packit.yaml
- Makefile
- README.md
- packaging/Containerfile.fedora
- packaging/rpm/flightctl-agent.spec
Enable packit for PRs, merges and releases:
commit merges to the main branch will be released in: https://copr.fedorainfracloud.org/coprs/g/redhat-et/flightctl-dev/ and can be enabled by using:
`dnf copr enable @redhat-et/flightctl-dev`
or importing the right repo: i.e.: https://copr.fedorainfracloud.org/coprs/g/redhat-et/flightctl-dev/repo/fedora-eln/group_redhat-et-flightctl-dev-fedora-eln.repo
New releases in github should be released in: https://copr.fedorainfracloud.org/coprs/g/redhat-et/flightctl/ and can be enabled by using:
`dnf copr enable @redhat-et/flightctl`
or importing the right repo: i.e.: https://copr.fedorainfracloud.org/coprs/g/redhat-et/flightctl/repo/fedora-eln/group_redhat-et-flightctl-fedora-eln.repo
Packit takes care of creating transient repositories for the PRs
> Enabling packit for PRs

- cmd/flightctl-server/main.go
- internal/server/server.go
This PR creates a new server object and breaks out the actual server generation logic to assist with testing. 
Depends on #73 
Related to #72
> internal: breakout Server logic from cmd/flightctl-server

- internal/agent/controller.go
- internal/agent/controller/containers.go
- internal/agent/controller/systemd.go
- internal/agent/controller/systeminfo.go
This appears to be unused code and creates a circular dep on the agent which blocks test creation.
> internal/agent/controller: remove agent dependency

- .github/dependabot.yml
This PR adds a prefix of `NO-ISSUE` to dependabot commits.
In addition, added docker ecosystem to scan containerfiles.
> NO-ISSUE: Dependabot commit prefix and docker ecosystem

- cmd/flightctl-server/main.go
- cmd/flightctl/approve.go
- cmd/flightctl/main.go
- go.mod
- internal/agent/config.go
- internal/client/config.go
- internal/client/config_test.go
- internal/config/config.go
Adds a config file encapsulates API client information (server URL, CA bundle, user auth), writes that file to `~/.flightctl/client.yaml` when the server starts, updates the `flightctl` CLI client to use that file.
> Add API client config file

- Makefile
This PR fixes a bug where a test overide to `GO_UNITTEST_FLAGS` with -race flag was committed. It also cleans up the population of the `coverprofile` and  `junitfile` artifacts into the the reports directory. The Ginkgo specific ENV have been removed for now as they are run directly by gotestsum. In the future we can use full ginkgo test invocation for e2e tests.
> NO-ISSUE: Makefile: fix override of GO_UNITTEST_FLAGS

- Containerfile
The ubi-micro is really small but does not contain the ca-certificates package.
This is necessary to authenticate public git servers contacted from the flightctl-server, otherwise it is impossible for our server to validate the TLS cert from github.com i.e.
Co-Authored-by: Mario Parra de Miguel <mparrade@redhat.com>
> NO-ISSUE: Include public ca-certificates

- Makefile
We introduce an intermediate empty target that depends on go.mod,
go.sum and the go files of the project.
The rebuild has become more evident during the work to deploy with kind+helm.
> MGMT-16972 Avoid rebuilding the server container every time we deploy

- .github/workflows/pr-smoke-testing.yaml
- .github/workflows/unit-tests.yaml
- Makefile
- README.md
- deploy/deploy.mk
- deploy/helm/flightctl/templates/flightctl-db-deployment.yaml
- deploy/helm/flightctl/templates/flightctl-db-service.yaml
- deploy/helm/flightctl/templates/flightctl-server-certs-persistentvolumeclaim.yaml
- deploy/helm/flightctl/templates/flightctl-server-config.yaml
- deploy/helm/flightctl/templates/flightctl-server-deployment.yaml
- deploy/helm/flightctl/templates/flightctl-server-route.yaml
- deploy/helm/flightctl/templates/flightctl-server-service.yaml
- deploy/helm/flightctl/values.kind.yaml
- deploy/helm/flightctl/values.yaml
- deploy/podman/compose.yaml
- examples/repository.yaml
- hack/create_cluster.sh
- hack/deploy_with_helm.sh
- hack/install_helm.sh
- hack/install_kind.sh
- hack/kind_cluster.yaml
- hack/wait_for_postgres.sh
This pull request moves the deployment of flightctl-server and db to use the existing
helm charts which have been tuned to allow conditional deployment in kind, and conditional deployment of the server.
This also adds the capability for the flightctl cmdline to use other servers based on the ~/.fligthctl/client.yaml config
Other services like keycloak, or metrics also need to be deployed with helm, but that will be addressed in a follow up patch as this one is already lengthy enough.
> MGMT-16972 Deploy via kind+helm

- cmd/flightctl-agent/main.go
If the agent can't access or create configuration it crashes with a panic/segfault. This provides a more meaningful error output.
> MGMT-17093: fix cryptic flightctl-agent crashes

- internal/agent/device/config/controller.go
Without this the code responsible for writing the enrollment banner to /etc/issue.d/flightctl-banner.issue will not work, assuming that we are using the device simulator.
> Pass down the enrollmentUIEndpoint to agent controller

- internal/agent/agent_test.go
- internal/agent/device/config/bootstrap.go
- internal/agent/device/config/controller.go
- internal/agent/device/writer/writer.go
The manager client is only initialized for the agent controller only on bootstrap. Subsequent boots won't initialize the reference neither will print the management QR. This commit fixes the issue.
> MGMT-17100: Fix enrolled device reboot crash

- internal/agent/agent_test.go
- internal/agent/testdata/device.yaml
Refactor the tests into ginkgo before adding more tests.
This makes use of the test harness, and segments the features being tested, although it adds some level of repetition to what we execute on the tests, this helps isolate better why an specific test could be failing.
> MGMT-17100 Convert agent tests into Ginkgo

- internal/agent/agent_test.go
- internal/service/enrollmentrequest.go
This fix ensures that device has the requested labels and adds E2E regression tests.
> MGMT-17053: Fix device labels on EnrollmentRequest approval

- internal/agent/device/config/bootstrap.go
- packaging/systemd/flightctl-agent.service
Flightctl-agent service notifies readiness way before the enrollment QR code is written in the issue directory. The systemd service is supposed to get active before getty, but it depends on the intervals from the config file.
> MGMT-17137: Add systemd notify to ensure enrollment QR is ready

- internal/store/fleet.go
- internal/tasks/resourcesync_test.go
We can safely remove the `owner=nil` line in the store, since we do the same thing at the API layer to prevent users from overwriting the owner.
> MGMT-17157: Fixed an issue where owner was not set via RS task

- Makefile
This PR allows the Makefile timeout to be configurable on a per test basis
> NO-ISSUE: expose timeout ENV.

- packaging/debian/changelog
- packaging/debian/rules
- packaging/rpm/flightctl-agent.spec
```
3T10:41:48Z" level=fatal msg="Error validating config: data-dir: path does not exist: /var/lib/flightctl" func=main.NewAgentCommand file="/builddir/b>
Main process exited, code=exited, status=1/FAILURE
```
Agent throws this error when using default data-dir. This should be fixed in packaging step.
> NO-ISSUE: Fix default data-dir does not exist

- cmd/flightctl-server/main.go
- internal/crypto/cert.go
- internal/server/server.go
- internal/server/server_test.go
- internal/server/tls.go
- test/harness/test_harness.go
- test/util/util.go
From the http server, every time a connection is served make sure that we gather the TLS client certificate details and put the CommonName in the context, so it's accessible later down when serving the API request.
Additionally when creating client certificates, define different common names for a client-admin key/cert, and for general agent bootstrapping certificates in a way that we can differentiate the origin of requests.
> NO-ISSUE: Gather client cert CN and create separate certs

- internal/client/config.go
- internal/client/config_test.go
* Adds support for reading client credentials from files via client.yaml (in addition to inlining)
* Adds validation of client.yaml
> NO-ISSUE: Support credentials from files, add validation

- deploy/deploy.mk
- hack/deploy_with_helm.sh
- hack/prepare_agent_config.sh
This exposes the service over the local address of our ethernet/wifi interface, by finding the exit route IP.
Then it prepares this configuration along with the certificates into the bin/agent/ directory for later image embedding.
> NO-ISSUE: Create an agent config we can use

- hack/Containerfile.local
We have a problem because BIB still does not support local registries. We'll figure out a way.
> NO-ISSUE: Add local Containerfile for e2e testing purposes

- internal/agent/agent.go
- internal/agent/device/status/conditions.go
- internal/agent/device/status/status.go
- internal/client/management.go
Update status does not take a DeviceStatus but a Device with a Status. This gets resolved by using static types vs bytes,
Manually verified tracking new test. https://github.com/flightctl/flightctl/issues/189
> MGMT-16600: fix status updates

- Makefile
- README.md
- deploy/agent-vm.mk
This commit enables the agent-vm and image building, it requires sudo root privileges, and libvirtd/virt-install tools.
> NO-ISSUE: Allow agent-vm and image targets

- .github/actions/setup-dependencies/action.yaml
- .github/workflows/pr-e2e-testing.yaml
- .github/workflows/pr-smoke-testing.yaml
- .github/workflows/unit-tests.yaml
- Makefile
- README.md
- deploy/agent-vm.mk
- hack/build_rpms.sh
- hack/build_rpms_packit.sh
* Refactor common github ci setup to an action
* Enable a basic E2E job with VM testing
* Enable unit tests over podman-compose again (since we needed podman4 for e2e, it's available)
> NO-ISSUE: Check agent VM boot on CI

- go.mod
- go.sum
v0.49.1 seems to have been re-tagged upstream and the caching of goproxies and github is causing issues.
We should stay on v0.49.0 until v0.49.2 is released.
Related-Issue: https://github.com/google/cadvisor/issues/3508
> Revert cadvisor to v0.49.0

- docs/architecture/tasks.md
- internal/tasks/fleet_selector.go
- internal/tasks/manager.go
Also fixed a bug that deleting a device should trigger the task that updates device ownership (important in case there are overlapping selectors, so the Fleet's Conditions can be updated if fixed).
> NO-ISSUE: Create doc about async service tasks

- internal/service/repository.go
- internal/store/fleet.go
- internal/store/repository.go
- internal/store/repository_test.go
- internal/tasks/fleet_rollout.go
- internal/tasks/fleet_selector.go
- internal/tasks/fleet_validate.go
- internal/tasks/fleet_validate_test.go
- internal/tasks/manager.go
- internal/tasks/repotester/repotester_test.go
- internal/tasks/templateversion_populate.go
Two commits:
MGMT-17323: Update fleet condition upon repository update
When a repository is created/updated/deleted, update the Condition of
any Fleet that references it. If the Fleet is valid, create a new
TemplateVersion.
NO-ISSUE: Better organize async tasks
Rename tasks to <resource>-<verb> for consistency.
Split "templateversion" task into two separate tasks since they were
essentially unrelated.
> MGMT-17323: Update fleet condition upon repository update

- Makefile
By caching the go mod downloads in the bin directory.
> NO-ISSUE: Improve flightctl-server container build times

- deploy/helm/flightctl/values.yaml
The image in https://quay.io/cloudservices/postgresql-rds is not available anymore.
We switched to quay.io/sclorg/postgresql-12-c8s:latest from the software collections repository.
https://github.com/sclorg
> NO-ISSUE: Fix database image for CI/local deployment

- .github/actions/setup-dependencies/action.yaml
- .github/workflows/pr-e2e-testing.yaml
- hack/prepare_agent_config.sh
- internal/cli/helpers.go
- internal/client/config.go
- test/e2e/agent_test.go
- test/harness/e2e/harness.go
- test/harness/e2e/vm/domain-template.xml
- test/harness/e2e/vm/vm.go
- test/harness/e2e/vm/vm_linux.go
- test/test.mk
This PR extends the basic E2E harness including the admin API
client, and moves the two e2e agent tests to the new harness
As an example where the API is required introduces a new test that:
* Verifies the TPM reporting from within the VM
This also switches the runner for E2E to the ginkgo binary which
produces better reporting console output as well as better junit output.
> NO-ISSUE: E2E Full harness (with API) + test for checking TPM status reporting

- Containerfile
- Makefile
The go-cache in bin/go-cache creates issues with the linter and other processes. And Copying the whole directory is slow when we have artifacts in bin/
We could use dockerignore and be less explicit but then we cannot copy some artifacts that we need from bin/ for other container builds.
> Optimize flightctl-server-container build

- deploy/helm/flightctl/templates/flightctl-db-deployment.yaml
Otherwise the DB runs out of memory and eventually gets killed because our demo cloud will apply default resource constraints of 512Mb and very little CPU.
> NO-ISSUE: Increase DB container resource request

- internal/experimental/experimental.go
- internal/experimental/experimental_test.go
- test/util/util.go
This PR adds a simple mechanism for the agent and service to enable experimental features based on the existence of `FLIGHTCTL_EXPERIMENTAL_FEATURES_ENABLED` with a non-empty value.. 
usage
```
experimentalFeatures := experimental.NewFeatures()
if experimentalFeatures.IsEnabled() {
// do potentially unstable things 
}
```
OCP ref. https://github.com/openshift/installer/blob/294318e39b4ba31a16f87fed688134fee51dd6c2/cmd/openshift-install/create.go#L204C15-L204C67
> MGMT-17847: internal/experimental: add support for experimental features

- test/harness/e2e/vm/domain-template.xml
On some fedora hosts the enrollment keys installed through libvirt into the UEFI firmware are incomplete or incorrect and we cannot boot our images.
So we leave secureboot enabled for the attestation part, but we disable enforcing signature checks by not installing secureboot keys.
> NO-ISSUE: Fix E2E VM boot on fedora hosts

- internal/tasks/device_render.go
- internal/tasks/git_helpers.go
The code supported cloning branches and tags, but there is no concept in git for cloning a hash. Fixed the code to perform a "checkout" after clone in case a hash is requested.
Note that until now there was an optimization of passing "depth=1" which means pulling with no history, but this means we can't check out hashes. We will optimize later when implementing a cache.
> MGMT-18036: Fix fetching git hashes

- .github/workflows/pr-e2e-testing.yaml
- Makefile
- deploy/agent-vm.mk
- deploy/deploy.mk
- deploy/helm/e2e-extras/templates/registry-deployment.yaml
- deploy/helm/e2e-extras/values.kind.yaml
- test/README.md
- test/scripts/agent-images/Containerfile-e2e-base.local
- test/scripts/agent-images/Containerfile-e2e-v2.local
- test/scripts/agent-images/Containerfile-e2e-v3.local
- test/scripts/agent-images/README.md
- test/scripts/agent-images/agent-images.mk
- test/scripts/agent-images/create_agent_images.sh
- test/scripts/agent-images/test-e2e-another-dummy.service
- test/scripts/agent-images/test-e2e-crashing.service
- test/scripts/agent-images/test-e2e-dummy.service
- test/scripts/create_e2e_certs.sh
- test/scripts/deploy_with_helm.sh
- test/scripts/kind_cluster.yaml
- test/scripts/prepare_agent_config.sh
- test/test.mk
* Setups an E2E CA and registry service certificates that the agents will trust
* Creates several agent image variants and pushes them all to the registry
> OCTOET-412: E2E registry bootc images

- internal/cli/delete.go
- internal/cli/get.go
- internal/service/templateversion.go
- internal/store/common.go
- internal/store/model/resource.go
- internal/store/model/templateversion.go
- internal/store/store.go
- internal/store/templateversion.go
- internal/tasks/fleet_validate.go
- internal/tasks/manager.go
- test/integration/store/templateversion_test.go
4 commits:
1. Fix "templatevesions" typo in CLI
2. TemplateVersions were not being deleted after the associated fleet is.  This is a symptom of the TV schema not having the fleet as a foreign key as it should. This commit adds the foreign key with cascading delete.
3. Listing template versions in the CLI did not apply the filter by fleetname, and returned TVs belonging to other fleets.
4. (unrelated) singular/plural message on invalid fleet
> MGMT-18037: Fix TemplateVersion issues

- test/e2e/agent_test.go
Sometimes a test can fail, and we know something is wrong with the flightctl-agent, gathering logs from the flightctl-agent would be helpful in that situation.
This pach retrieves and prints the flightctl-agent status and logs in case of test failure.
> NO-ISSUE: Better debug details on E2E failure

- internal/agent/config.go
- internal/client/config.go
- internal/client/config_test.go
- test/harness/test_harness.go
- Introduces FLIGHTCTL_TEST_ROOT_DIR env var to make the test root dir configurable.
- Allows client config file to contain relative paths to certs.
- Adds Equal() and DeepCopy() methods to client config.
> NO-ISSUE: Client config improvements

- internal/store/common.go
- internal/store/device.go
- internal/store/fleet.go
- internal/store/model/device.go
- internal/store/model/fleet.go
- internal/store/model/repository.go
- internal/store/repository.go
- internal/tasks/common.go
- internal/tasks/device_render.go
- internal/tasks/fleet_validate.go
- internal/tasks/manager.go
- internal/tasks/repo_update.go
- test/integration/store/device_test.go
- test/integration/store/fleet_test.go
- test/integration/store/repository_test.go
- test/integration/store/resourcesync_test.go
- test/integration/store/templateversion_test.go
- test/integration/tasks/fleet_rollout_test.go
- test/integration/tasks/fleet_validate_test.go
- test/integration/tasks/repo_update_test.go
- test/util/create_utils.go
Two commits:
- MGMT-18098: Track references of fleets/devices to repositories
Create a join table in SQL and update references from fleets and
standalone devices to repositories. Later, when a repository is updated
we can immediately know which fleets and devices are affected.
- MGMT-17945: Refresh devices/fleets upon repo update
If a repository resource is updated, make sure to:
1. Create a new TemplateVersion for each fleet that references it
2. Render each standalone device that references it
> Refresh devices/fleets upon repo update

- internal/store/model/device.go
- internal/store/model/fleet.go
- internal/store/model/repository.go
- internal/tasks/git_helpers.go
- test/integration/store/device_test.go
- test/integration/store/fleet_test.go
- test/integration/store/repository_test.go
Deleting devices, fleets, and repos was failing due to foreign key constraints introduced by the many-to-many relationships. This fixes the issue by adding cascading deletes so that when a resource is deleted, the associated entry in the join table is also deleted.
> MGMT-18185: Fix deletion errors

- internal/tasks/device_render.go
- internal/tasks/fleet_validate.go
- test/integration/tasks/fleet_validate_test.go
1. Combined the code that validates a fleet template and the code that renders a device since they are very similar.
2. Add an error message to the condition if validation fails.
> MGMT-18179: Remove duplication between config validate and render

- internal/agent/device/status/status_test.go
- internal/client/enrollment.go
- internal/client/management.go
This PR ensures response bodies are closed for HTTP client requests. Failure to do so can result in resource leaks and I believe this is a possible root cause of the observed memory leak.
The benchmark was added to validate that the leak was not from status collection. This benchmark can be used in the future to ensure memory allocations and time complexity are kept in check.
> NO-ISSUE: client: make sure to close response body

- deploy/helm/flightctl/templates/flightctl-server-config.yaml
- deploy/helm/flightctl/templates/flightctl-server-deployment.yaml
- deploy/helm/flightctl/templates/flightctl-server-service.yaml
- deploy/helm/flightctl/values.kind.yaml
- deploy/podman/config.yaml
- internal/agent/config.go
- internal/client/config_test.go
- internal/config/config.go
- test/scripts/kind_cluster.yaml
Since #303 is changing configuration and being slightly disruptive for existing images and configurations, we are using the opportunity to change the server API port to a port that indicates we are using TLS (3443 in this case).
> NO-ISSUE: Move service port to a port that indicates TLS

- internal/tasks/config_helpers.go
- internal/tasks/config_helpers_test.go
- internal/tasks/device_render.go
- internal/tasks/fleet_rollout.go
- internal/tasks/templateversion_populate.go
- test/integration/tasks/fleet_rollout_test.go
- test/integration/tasks/templateversion_populate_test.go
- test/util/create_utils.go
At this point, the only parameters recognized are of the form {{ device.metadata.labels[key] }}, and the service will replace that with the label value corresponding to the specified key for each device.
Parameters in gitConfig and inlineConfig are replaced upon rollout. Errors are currently logged but not reported to users - this will be fixed in a followup.
For gitConfig, parameters in TargetRevision require special handling and will be handled in a followup.
Outline of changes:
1. When validating fleets: do not validate ignition format if inline config contains parameters.
2. When populating templateVersion: remove redundant validations of inline configs.
3. When populating templateVersion: propogate the error when setting the status.
4. When rolling out a templateVersion to a fleet: …
> MGMT-18196: Replace parameters upon fleet rollout

- .github/workflows/pr-smoke-testing.yaml
- go.mod
- go.sum
- internal/cli/apply.go
- internal/cli/approve.go
- internal/cli/delete.go
- internal/cli/get.go
- internal/cli/global.go
- internal/cli/helpers.go
- internal/util/util.go
This is a start of a series of small improvements to the CLI. This PR contains:
- Add structure for global options.
- Switch reading the client config from the OS's standard config directory (on Linux `$HOME/.config/flightctl/client.yaml`).
- Add a `-c/--context`global option that allows to select between multiple client config files.
- Add new statuses and other fields to the output of `flightctl get`.
> Cli improvements

- internal/agent/device/device.go
- internal/tasks/device_render.go
The agent verifies the version of the ign is valid during deserialization so currently on renderedVersion 1 the agent fails in the steady state until another renderedVersion is sent. This PR 
- ensures a valid version is sent for empty config, ParseCompatibleVersion strips the version.
- continue on error bug found while debugging steady state.
> NO-ISSUE: tasks: ensure empty ignition has a version

- api/v1alpha1/validation.go
- internal/util/validation/validation.go
We are getting an error where the generic repo is being validated, but it does not allow either the sshConfig or httpConfig object.
> NO-ISSUE: Add simple validation for different Repo types

- internal/tasks/callback_manager.go
- internal/tasks/fleet_rollout.go
1. If a device's labels change, trigger the existing single device rollout task
2. No longer assume that if a device is at the correct TemplateVersion then there is no work to be done. Replace the parameters and then compare the old and new specs instead.
> MGMT-18199: Re-render devices upon label change

- api/v1alpha1/validation.go
- internal/service/fleet.go
Currently, a fleet's device template configuration items are only partially validated.
I completed the validations by adding the OS image and config template validations.
Alternatively, would it be better to validate the entire spec, by invoking the same validation method for a device spec?
Note: The UI does not validate the OS image using the regexp yet, it's tracked separately.
> NO-ISSUE: Validate the device template settings of a fleet

- .github/workflows/pr-e2e-testing.yaml
This is needed because e2e has been failing from no space on device
```
cp: error copying '/store/stage/uuid-ae0e4adf8b0c45fbbed26150f7e4df8b/data/tree/./disk.qcow2' to '/output/qcow2/./disk.qcow2': No space left on device
```
ref. https://github.com/flightctl/flightctl/actions/runs/9910087335/job/27379656537?pr=353
> NO-ISSUE: e2e: enable free disk space step

- internal/periodic_checker/server.go
- internal/store/device.go
- internal/tasks/device_disconnected.go
- internal/tasks/device_liveness.go
This PR adds a simple MVP periodic task that checks the device `updatedAt` timestamp and sets the status to `Unknown` if it has not reported in more than 5 minutes. 
manually tested
`<shutdown device>`
```
time="2024-07-11T18:52:31Z" level=info msg="Updating 0 devices to unknown status" func="github.com/flightctl/flightctl/internal/tasks.(*DeviceLiveness).Poll" file="/app/internal/tasks/device_liveness.go:59"
time="2024-07-11T18:54:31Z" level=info msg="Running RepoTester" func="github.com/flightctl/flightctl/internal/tasks.(*RepoTester).TestRepositories" file="/app/internal/tasks/repotester.go:43" request_id=repotester-000000000
time="2024-07-11T18:54:31Z" level=info msg="Running ResourceSync Polling" func="github.com/flightctl/flightctl/internal/tasks.(*ResourceSync).Poll" …
```
> MGMT-18371: add device summary status periodic

- deploy/helm/flightctl/templates/flightctl-api-config.yaml
- deploy/helm/flightctl/templates/flightctl-worker-clusterrole.yaml
- deploy/helm/flightctl/templates/flightctl-worker-clusterrolebinding.yaml
- deploy/helm/flightctl/values.yaml
- test/scripts/deploy_with_helm.sh
Makes the deployment of ClusterRole and CLusterRoleBinding for secret access optional, it's too wide for a cluster and many PAAS offerings won't accept this.
Related-Issue: #354
> GITHUB-354: Make ClusterRole and binding optional

- internal/store/enrollmentrequest.go
- internal/store/fleet.go
- internal/store/repository.go
- internal/store/resourcesync.go
- internal/tasks/resourcesync.go
- test/integration/store/enrollmentrequest_test.go
- test/integration/store/fleet_test.go
1. When the ResourceSync task updates the fleet spec, it should nil out some fields, just like the code in internal/service/fleet.go does
2. For CreateOrUpdate, we should always nil out the status.  This applies to other resources as well.
> EDM-177: ResourceSync overwrites fleet status on sync

- test/harness/e2e/vm/vm.go
Updated SSHCommand function with "PubkeyAuthentication=no" to avoid that any local SSH key is used for the authentication.
This will avoid a possible "Too many authentication failures" error when the test runs in local env
> NO-ISSUE: Update SSHCommand function in e2e

- internal/cli/approve.go
Currently, `flightctl approve` expects the server to return an HTTP 201 when the API specifies that it returns a HTTP 200. Correct this so that we don't get an error on successful enrollment request approval.
> EDM-178: Fix approve error checking

- internal/store/common_unittest_db.go
- internal/tasks/device_disconnected_test.go
- test/integration/store/device_test.go
- test/integration/store/enrollmentrequest_test.go
- test/integration/store/fleet_test.go
- test/integration/store/repository_test.go
- test/integration/store/resourcesync_test.go
- test/integration/store/templateversion_test.go
- test/integration/tasks/fleet_rollout_test.go
- test/integration/tasks/fleet_selector_test.go
- test/integration/tasks/fleet_validate_test.go
- test/integration/tasks/repo_update_test.go
- test/integration/tasks/repotester_conditions_test.go
- test/integration/tasks/templateversion_populate_test.go
This PR adds a benchmark for testing performance improvements. The bench assumes worst-case scenario where all devices must have status updated. The majority of the time is spent in writing the update.
```
name                                                          time/op
DeviceDisconnectedPoll/update_summary_status_1000_devices-12  87.5ms ±20%
DeviceDisconnectedPoll/update_summary_status_2000_devices-12   183ms ± 6%
DeviceDisconnectedPoll/update_summary_status_5000_devices-12   486ms ±11%
name                                                          alloc/op
DeviceDisconnectedPoll/update_summary_status_1000_devices-12  4.26MB ± 0%
DeviceDisconnectedPoll/update_summary_status_2000_devices-12  8.53MB ± 0%
DeviceDisconnectedPoll/update_summary_status_5000_devices-12  21.3MB ± 0%
name …
```
> NO-ISSUE: tasks add device disconnected bench 

- .github/workflows/publish-containers.yaml
- deploy/helm/flightctl/Chart.yaml
- deploy/helm/flightctl/templates/flightctl-api-deployment.yaml
- deploy/helm/flightctl/templates/flightctl-periodic-deployment.yaml
- deploy/helm/flightctl/templates/flightctl-worker-deployment.yaml
- deploy/helm/flightctl/values.kind.yaml
- deploy/helm/flightctl/values.yaml
By packaging the appVersion latest-${git-sha} we make sure that every release of the charts gets tied to an specific version of our code, and can be deployed with the corelated images.
> EDM-202: Correct helm packaging and make image tags follow appVersion

- internal/cli/helpers.go
```
avishay@fedora:~/work/flightctl$ bin/flightctl get dev
NAME								OWNER		SYSTEM	UPDATED	APPLICATIONS	LAST SEEN
f62dfb4f5d2cdbb9339362b5f18f2ce268d75649bdc80003f0e04292a7ef8c3	Fleet/default	Unknown	Unknown	Unknown		<never>
f68dfb5f5d2cdbb9339363b7f19f3ce269d75650bdc80004f1e04293a8ef9c4	<none>		Unknown	Unknown	Unknown		<never>
fab9839018890a88b898b980f8f809f8e8ac333761977d987a777a777a987c	Fleet/fleet-b	Unknown	Unknown	Unknown		<never>
avishay@fedora:~/work/flightctl$ bin/flightctl get er
NAME								APPROVAL	APPROVER	APPROVED LABELS
13d632d8633782719874da4052f957faa742fc7050026748bc79065c8819d1b	Pending		<none>		
ab238b7190128394809b809a0b980231984b098c0983408aa8a8a0809800991	Pending		<none>		
avishay@fedora:~/work/flightctl$ bin/flightctl get flt
NAME	OWNER				SELECTOR	VALID
default …
```
> NO-ISSUE: Short names for resources in the CLI

- internal/tasks/device_render.go
- internal/tasks/templateversion_populate.go
- test/integration/agent/agent_test.go
When handling kubernetes secrets, they are currently expected to be base64 encoded. But the data itself as received in kubernetes API is not encoded since JSON decodes it before the data can be handled by the caller. So the current base64 decoding should be removed.
> EDN-221: Secret data should not be decoded

- internal/agent/device/console.go
- internal/agent/device/device.go
- internal/agent/device/resource/common.go
- internal/agent/device/resource/common_test.go
- internal/agent/device/resource/controller.go
- internal/agent/device/resource/cpu.go
- internal/agent/device/resource/cpu_test.go
- internal/agent/device/resource/disk.go
- internal/agent/device/resource/disk_test.go
- internal/agent/device/resource/memory.go
- internal/agent/device/resource/memory_test.go
- internal/agent/device/resource/mock_resource.go
- internal/agent/device/resource/resource.go
- internal/agent/device/status/resources.go
This PR
- simplifies resource monitor logic by breaking out shared code.
- fixes flakey monitor tests
- additional unit tests
- race cleanup
- ensures the status message is taken from the alert description cc @avishayt 
- status improvements/bug fixes
notes:
I validated tests with 500 iterations with `-race` flag and achieved zero percent failure
```
go test -v -race -count=500 ./internal/agent/device/resource/...
PASS
ok      github.com/flightctl/flightctl/internal/agent/device/resource   454.768s
```
During an alert the device summary status will go Degraded and the message will be generated like below or populated by the user if a description is provided.
```json
"resources": {
"cpu": "Unknown",
"disk": "Unknown",
"memory": "Warning"
},
"summary": {
"info": "Warning: Memory usage is …
```
> MGMT-18283: agent: harden resource monitoring

- internal/agent/device/resource/controller.go
- internal/agent/device/resource/mock_resource.go
- internal/agent/device/resource/resource.go
This PR adds a first pass to define default alert thresholds for CPU disk and memory. This is functional and improves the current UI UX which shows `Unknown` by default to now reports `Healthy` assuming the alerts are not firing.
status
```json
"resources": {
"cpu": "Healthy",
"disk": "Healthy",
"memory": "Healthy"
}
```
disk
```go
AlertRules: []v1alpha1.ResourceAlertRule{
{
Severity:    v1alpha1.ResourceAlertSeverityTypeCritical,
Percentage:  90,
Duration:    "10m",
Description: "", // use generated description
},
{
Severity:    v1alpha1.ResourceAlertSeverityTypeWarning,
Percentage:  80,
Duration:    "30m",
Description: "", // use generated description
}
},
Path: "/sysroot"
```
reference for sysroot: https://github.com/containers/bootc/blob/bc28c591c1f265f654821721047aa530e6d9617c/docs/sr …
> MGMT-18283: agent: add default resource alerts

- internal/agent/device/resource/disk_test.go
This change  modifies the disk selection so only file systems that represent "real" storage are accepted
> NO-ISSUE: When running disk testing with some file systems may cause the test to fail

- internal/client/config.go
Don't check the hostname length if we failed to parse the URL. This leads to the agent crashing.
> NO-ISSUE: Fix client config validation

- .packit.yaml
- Makefile
- hack/build_rpms_packit.sh
- packaging/rpm/flightctl.spec
Build RPMs in COPR recurrently for flightctl command line.
The CLI could be install with:
```
sudo dnf copr enable -y @redhat-et/flightctl-dev
sudo dnf install -y flightctl
```
> EDM-234: Build RPM for FlightCtl CLI

- Makefile
- go.mod
- go.sum
- internal/agent/device/status/exporters_linux.go
- internal/agent/device/status/exporters_non_linux.go
- internal/agent/device/status/exporters_other.go
- internal/agent/device/status/status.go
- internal/agent/device/status/systeminfo.go
This PR removes cadvisor as a dep and gates linux specific agent logic with build targets. Resource collectors are linux opinionated and disabled for all non-linux builds.
> NO-ISSUE: agent: remove cadvisor as a dep and add non linux build targets

- test/scripts/agent-images/Containerfile-e2e-base.local
part of rollback MVP is greenboot support so let's add it to the base image.
> MGMT-17001: install greenboot into agent base image

- go.mod
- go.sum
- internal/api_server/agentserver/grpc.go
- internal/cli/approve.go
- internal/cli/console.go
Reverts flightctl/flightctl#416
The gRPC endpoint is agent-only , and the agent does not have/cannot have a token, it's only mTLS.
having the UI/CLI talk to that gRPC is an interim solution to have something now, and we should eventually have it as a websocket endpoint on the main API (with the regular token auth).
I need to revert this because it breaks the agent gRPC connection.
> Revert "NO-ISSUE: Enable token auth for terminal grpc connection"

- .github/workflows/publish-cli-bins.yaml
- Makefile
- pkg/version/version.go
On push to main, create a GitHub release of the flightctl CLI for {Linux, Darwin} on {amd64, arm64}. Since we do not currently have versioning, the releases are named "flightctl-cli-[year][month][day]-[commit hash]"
> EDM-276: Add workflow to publish cli binary releases

- .github/workflows/publish-cli-bins.yaml
The Flightctl repo disables all GitHub Actions write permissions by default. Enable them so our workflow can publish the binary releases.
> EDM-276: Fix token permissions for release publication

- internal/tasks/config_helpers.go
- internal/tasks/config_helpers_test.go
- internal/tasks/device_render.go
- internal/tasks/fleet_rollout.go
- internal/tasks/fleet_validate.go
- internal/util/util.go
- test/integration/tasks/fleet_validate_test.go
If a fleet template contains a parameter with invalid syntax, set its Valid condition to false.
Also, ensure device specs don't contain parameters.
> MGMT-18250: Set fleet as invalid for bad parameter

- .github/workflows/publish-cli-bins.yaml
- .github/workflows/publish-containers.yaml
- Makefile
Make the following changes to the "Release CLI Binaries on GH" workflow
- Release checksums
- Mark release as pre-release
- Delete all previous releases
- Change release name format from "flightctl-cli-DATE-HASH" to "latest"
> EDM-276: Release workflow improvements

- internal/agent/device/config/common.go
- internal/agent/device/config/controller.go
- internal/agent/device/config/controller_test.go
- internal/agent/device/device.go
- internal/agent/device/fileio/writer.go
This is really a bug today we only add new configs we don't purge
TODO:
> EDM-327: agent: ensure stale configs are removed on sync

- packaging/greenboot/flightctl-agent-running-check.sh
- packaging/rpm/flightctl.spec
The script checks if the flightctl-agent.service is active and running without failure. It waits for the service to become active within a specified timeout (60s) and ensures it remains running for an additional duration (60s). If the service fails or does not become active in time, the script aborts exiting non 0 with an error message.
- On failure 1,2 greenboot will reboot
- On on failure 3 it will rollback if available.
Testing: manually tested
> MGMT-17001: add support for greenboot rollback on agent service failure

- deploy/helm/flightctl/values.yaml
The auth parameters are used in the helm charts as: Values.api.auth.*
but the default values.yaml has auth at top level: Values.auth.*
This will fix it. The error was not caught in kind because values.kind.yaml had the values at the right level.
> Fix helm values.yaml

- internal/store/certificatesigningrequest.go
- internal/store/model/certificatesigningrequest.go
- internal/store/store.go
This is a prereq for being able to add the correct logic to the CSR API paths in [`internal/service`](https://github.com/flightctl/flightctl/blob/main/internal/service/certificatesigningrequest.go). So far it is modeled on the enrollment request.
> MGMT-18558: Add CSR model to internal store / database

- internal/api_server/middleware/tls.go
Sometimes we have failed TLS handshakes on the server but it's not possible to get any reasonable information on the nature of the failure.
This will help us debugging consoel issues.
> EDM-341: Provide additional info on failed TLS connections

- .github/workflows/publish-containers.yaml
- deploy/helm/flightctl/Chart.yaml
- hack/publish_charts.sh
This makes the charts compatible with ArgoCD usage, since ArgoCD expects a base OCI repo like this.
Also makes the helm charts publishing depending on the publishing of the containers. (Otherwise we would render helm charts that point to a container version that has not been published)
> EDM-297: Publish helm charts under quay.io/flightctl/charts

- cmd/flightctl-agent/main.go
- pkg/log/log.go
This pr improves the prefix logger providing proper caller context which is critical for debug.
```
time="2024-08-15T23:51:19Z" level=info msg="Enrollment request not yet approved" func="github.com/flightctl/flightctl/pkg/log.(*PrefixLogger).Info" file="/home/sbatsche/projects/flightctl/flightctl/flightctl/packaging/rpm/flightctl-latest/pkg/log/log.go:45"
```
```
time="2024-08-16T00:12:33.357585Z" level=info msg="Enrollment request not yet approved" file="agent/device/bootstrap.go:272"
```
> EDM-349: ensure prefix logger shows caller context

- .github/workflows/publish-cli-bins.yaml
- Makefile
Add build-cli Makefile target that only builds flightctlc cli.
Check that PRs can build flightctl by running the cli build workflow without publishing anything.
> NO-ISSUE: Improve CLI publish workflow

- deploy/helm/flightctl/templates/flightctl-api-certs-persistentvolumeclaim.yaml
- deploy/helm/flightctl/templates/flightctl-api-config.yaml
- deploy/helm/flightctl/templates/flightctl-api-deployment.yaml
- deploy/helm/flightctl/templates/flightctl-api-route-agent-grpc.yaml
- deploy/helm/flightctl/templates/flightctl-api-route-agent.yaml
- deploy/helm/flightctl/templates/flightctl-api-route.yaml
- deploy/helm/flightctl/templates/flightctl-api-service-agent-grpc.yaml
- deploy/helm/flightctl/templates/flightctl-api-service-agent.yaml
- deploy/helm/flightctl/templates/flightctl-api-service.yaml
- deploy/helm/flightctl/templates/flightctl-db-deployment.yaml
- deploy/helm/flightctl/templates/flightctl-db-networkpolicy.yaml
- deploy/helm/flightctl/templates/flightctl-db-persistentvolumeclaim.yaml
- deploy/helm/flightctl/templates/flightctl-db-service.yaml
- deploy/helm/flightctl/templates/flightctl-periodic-config.yaml
- deploy/helm/flightctl/templates/flightctl-periodic-deployment.yaml
- deploy/helm/flightctl/templates/flightctl-rabbitmq-service.yaml
- deploy/helm/flightctl/templates/flightctl-rabbitmq-statefulset.yaml
- deploy/helm/flightctl/templates/flightctl-worker-clusterrole.yaml
- deploy/helm/flightctl/templates/flightctl-worker-clusterrolebinding.yaml
- deploy/helm/flightctl/templates/flightctl-worker-config.yaml
- deploy/helm/flightctl/templates/flightctl-worker-deployment.yaml
- deploy/helm/flightctl/templates/flightctl-worker-serviceaccount.yaml
- deploy/helm/flightctl/values.kind.yaml
- deploy/helm/flightctl/values.yaml
- test/scripts/deploy_with_helm.sh
- test/scripts/prepare_agent_config.sh
* If not individually overriden domains are composed from .global.flightctl.baseDomain
* Image references equalized under image.{image,tag,pullPolicy}
* Added internal namespace support, while single namespace is still posible
* Uses .Release.namespace instead of a value-passed namespace
> EDM-295: Reorganize helm charts top down

- internal/store/store.go
Currently there is a cascade delete foreign key constraint on table "fleet_repos" which is used for the many to many relationship between table repositories and fleets.  This causes the association record to be deleted when repository is deleted (which is not desirable). This change removes the constraint during migration.  It means that the association will only be deleted when the fleet is deleted. Same change was done for table "device_repos".
> EDM-344: Fleet valid status is not set to 'false' if a repository present in its template config is deleted

- test/scripts/agent-images/create_agent_images.sh
since https://github.com/osbuild/bootc-image-builder/commit/1a79b1d6d17f91af6e07fa6db3f4f222ce38f0e6 `build` is the default subcommand which is a breaking change. this unblocks e2e
ref https://github.com/flightctl/flightctl/actions/runs/10459089773/job/28962282904
> NO-ISSUE: fix bootc-image-builder

- cmd/flightctl-agent/main.go
- internal/agent/device/bootstrap.go
```
Usage of bin/flightctl-agent:
flags
-config string
Path to the agent's configuration file. (default "/etc/flightctl/config.yaml")
commands:
version    Display version information
```  
```
level=info msg="System information: version=20240820-v0.1.0-5-g1f0daa1, go-version=go1.21.8, platform=linux/amd64, git-commit=1f0daa1"
```
```
bin/flightctl-agent version
Flightctl Agent Version: 20240820-v0.1.0-4-g6122840
Git Commit: 6122840
```
> EDM-361: agent: add version and debug metadata

- deploy/helm/flightctl/templates/flightctl-api-certs-persistentvolumeclaim.yaml
- deploy/helm/flightctl/templates/flightctl-db-persistentvolumeclaim.yaml
- deploy/helm/flightctl/templates/flightctl-rabbitmq-statefulset.yaml
- deploy/helm/flightctl/values.yaml
This commit leaves storageClassName at base global level for all subcharts to pick up.
> EDM-362: Keycloak storageClassName global fix

- internal/service/certificatesigningrequest.go
- internal/service/device.go
- internal/service/device_test.go
- internal/service/fleet.go
- internal/service/fleet_test.go
- internal/service/repository.go
- internal/service/repository_test.go
- internal/service/resourcesync.go
- internal/service/resourcesync_test.go
- internal/store/certificatesigningrequest.go
- internal/store/common.go
- internal/store/device.go
- internal/store/fleet.go
- internal/store/repository.go
- internal/store/resourcesync.go
- internal/tasks/fleet_rollout.go
- internal/tasks/fleet_selector.go
There are cases where we should fail when updating a resource that no longer exists, but today we recreate them due to races:
1. PATCH operations get the resource, modify it, and call the store to update it.  If the resource is deleted after getting it, we will recreate it.
2. When rolling out a fleet, a device that was deleted will be similarly recreated.
3. When updating a device owner upon label/selector change, we can similarly recreate a deleted device.
> EDM-322: CreateOrDelete can create deleted resources in a race

- deploy/helm/flightctl/charts/keycloak/templates/keycloak-ingress.yaml
- deploy/helm/flightctl/charts/keycloak/templates/keycloak-route.yaml
- deploy/helm/flightctl/charts/keycloak/values.yaml
- deploy/helm/flightctl/values.yaml
This fixes keycloak deployment on OpenShift until we have working ingresses again.
> EDM-363: Add route support for keycloak and use baseDomain

- internal/crypto/cert.go
- internal/service/agent/handler.go
- internal/service/certificatesigningrequest.go
During enrollment it should be possible to accept certificates created for such purpose through our CSR API.
> MGMT-18170: Accept enrollment certificates from the CSR API

- deploy/helm/flightctl/templates/flightctl-api-config.yaml
Same as flightctl-api endpoint, we need to add agent-grpc endpoint
> EDM-341: Add Agent GRPC endpoint to cert generation

- api/v1alpha1/openapi.yaml
- api/v1alpha1/spec.gen.go
- api/v1alpha1/types.gen.go
- internal/api/client/client.gen.go
- internal/api/server/server.gen.go
- internal/service/common.go
- internal/service/common_test.go
- internal/service/device.go
- internal/service/resourcesync.go
- internal/store/common.go
- internal/store/common_test.go
- internal/store/model/certificatesigningrequest.go
- internal/store/model/device.go
- internal/store/model/enrollmentrequest.go
- internal/store/model/fleet.go
- internal/store/model/repository.go
- internal/store/model/resourcesync.go
- internal/store/model/templateversion.go
- test/integration/store/device_test.go
This commit adds a filter allowing listing resourcesyncs by repository. This is needed by the UI.
The changes are:
1. Make the current status filter logic generic so that it can also filter specs.
2. Add the repository filter, internally implemented by the above filter logic.
3. Ensure that all specs and statuses are jasonb rather than bytea so that the filters work properly.
> EDM-387: Filter resourcesyncs by repository

- cmd/flightctl/main.go
- internal/cli/csrconfig.go
This will help users avoid manually having to create the `.yaml` file from their openssl-generated `.csr` file.
> MGMT-18170: Add CLI command to generate CSR resource config

- docs/user/getting-started.md
Fixes an inconsistency regarding the CSR expiry time.
Now the docs and the examples will all use an expiry time of 604800 seconds.
> MGMT-18170: Use same default expire time everywhere

- docs/user/getting-started.md
The docs should not reference an older version.
After speaking to @amir-yogev-gh , we agreed it would be better not to hardcode a version, but instead use a placeholder.
> Avoid hardcoded version in docs

- internal/agent/device/spec/spec_test.go
Adds some unit tests for the following methods inside the spec manager:
- NewManager 
- Initialize
- Ensure
This will be the first of a few prs seeking to improve  test coverage for the spec manager.
> EDM-373: Spec manager test coverage

- internal/agent/client/podman_compose.go
- internal/agent/device/hook/actions.go
- internal/agent/device/hook/default_hooks.go
- internal/agent/device/hook/manager.go
- internal/agent/device/hook/mock_manager.go
Add support for builtin hooks in addition to the existing support of api
hooks.
The builtin hooks are actualy functions that perform specific task.
This PR changes the implementation of podman-compose up and
podman-compose down to use builtin hooks
>  NO-ISSUE:  Add support for builtin hooks

- internal/agent/device/config/controller.go
- internal/agent/device/hook/actions.go
- internal/agent/device/hook/manager.go
- internal/agent/device/status/containers.go
- internal/util/util.go
This PR is a minor cleanup from POC, removes `samber/lo` as a dependency for the agent binary, and adds FromPtr to util.
> NO-ISSUE: agent: remove samber/lo as dep

- go.mod
- go.sum
- internal/cli/get.go
Adds an `-o wide` output format to the `flightctl get` command.
So far, only used when printing the devices table, then shows an additional "LABELS" column.
> EDM-507: Add -o wide to device table

- internal/agent/device/console/console.go
- internal/api_server/agentserver/grpc.go
- internal/cli/console.go
- internal/consts/consts.go
The agent console was importing api_server for a couple consts, which was causing all the gorm and postgres modules to be included in the agent.  Moving these consts causes the agent to go from 35 to 24MB.
> NO-ISSUE: Move GRPC consts to separate package

- internal/service/device.go
- internal/store/common.go
- internal/store/device.go
- internal/store/fleet.go
- test/integration/store/device_test.go
- test/util/create_utils.go
There are a couple instances where we need to understand if device specs are being updated by the user.  reflect.DeepEqual doesn't work properly here because oneOf is translated to json.RawMessage, and comparing JSONs isn't reliable because properties aren't always sorted the same way. Instead, we use reflect.DeepEqual where possible, and unmarshal when necessary.
> EDM-546: Fix device spec comparisons

- deploy/helm/flightctl/templates/flightctl-api-config.yaml
```
Error: UPGRADE FAILED: template: flightctl/templates/flightctl-api-config.yaml:38:57: executing "flightctl/templates/flightctl-api-config.yaml" at <include "flightctl.getBaseDomain" (dict "noNs" "true")>: error calling include: template: flightctl/templates/_helpers.tpl:2:16: executing "flightctl.getBaseDomain" at <.Values.global.baseDomain>: nil pointer evaluating interface {}.global
```
when passing the dictionary with "noNS" we must also pass the current context to let it access .Values.global.baseDomain
> NO-ISSUE: Fix helm error on acm install

- deploy/helm/flightctl/values.kind.yaml
When merging main with #537, I accidentally changed the Prometheus server nodeport to the API server target port. Re-align this value with the 9090 value that kind and prometheus expect.
> NO-ISSUE: Fix Prometheus Nodeport in Kind

- deploy/helm/flightctl/templates/flightctl-api-networkpolicy.yaml
- deploy/helm/flightctl/templates/flightctl-networkpolicy.yaml
Otherwise once network policies are enabled, the flightctl services can talk to each other, but ingress can't talk to our API endpoints.
Fixes: https://issues.redhat.com/browse/EDM-463
> Enable flightctl-api access to to ingress

- deploy/helm/flightctl/templates/flightctl-prometheus-config.yaml
Filter discovered pods by port to only scrape those that use ports 15690 (API), 15691 (DB), and 15692 (RabbitMQ) and avoid unnecessary unconnected targets.
> EDM-603: Add prometheus target filters

- .github/workflows/publish-cli-bins.yaml
Current output of `gh release list | awk '/^latest\s/ { print $1 }'` appears to not properly pickup the existing `latest` tagged release which is resulting in a [gh actions failure](https://github.com/flightctl/flightctl/actions/runs/11441582895/job/31830014525) as we are trying to create the already existing `latest` release.
This updates the command used to find out if we have an existing release to explicitly use the gh cli tool to query tag names.
> NO-ISSUE: Fix updating existing latest gh release binaries

- docs/user/getting-started.md
At the moment, the UI version that is deployed as part of the flightctl main chart is [fixed](https://github.com/flightctl/flightctl/blob/main/deploy/helm/flightctl/Chart.yaml#L13).
For customers wanting to use the UI, we document how they can override the default version and where to find the available helm chart versions.
> Document how to modify the deployed UI version

- cmd/devicesimulator/main.go
This PR aids in observability of the auto enrollment process and ensures clients don't block forever by enforcing a 30s timeout.
> NO-ISSUE: debug sim

- docs/user/getting-started.md
- hack/check-commit-message.sh
Follow up to https://github.com/flightctl/flightctl/pull/601.
The links I added earlier were incorrect as they were pointing to the helm charts, and not to the UI applications themselves.
> Fix links to UI image versions, not helm charts

- internal/agent/device/applications/applications.go
- internal/agent/device/applications/applications_test.go
- internal/agent/device/applications/podman_monitor.go
- internal/agent/device/applications/podman_monitor_test.go
- internal/tasks/fleet_rollout.go
This PR adds missing support for `Completed` application status. Completed is defined as a container which starts then exits with a 0 exit code. In this case it should not be considered an error but instead expected/success. The resulting status from the fix is below.
```yaml
applications:
- name: compose-oci-example-complete
ready: 0/1
restarts: 0
status: Completed
applicationsSummary:
status: Healthy
```
> EDM-642: EDM-240: add support for completed applications status

- internal/agent/client/podman.go
previously we were using podman ps to check for networks the issue is if the container is stopped or died we will not cleanup the network. this PR resolves that by using network ls and filtering by label.
> EDM-240: ensure network cleanup if containers are stopped

- deploy/helm/flightctl/templates/flightctl-rabbitmq-statefulset.yaml
Exclude .erlang.cookie file from PV to fix the startup error:
```
Exception during startup:
error:{badmatch,{error,{{shutdown,{failed_to_start_child,auth,{"Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only",
```
> NO-ISSUE: fix rabbitmq pv path

- internal/agent/device/applications/podman_monitor.go
- internal/agent/device/applications/podman_monitor_test.go
We have had some serialization issues which could be the result of different versions of podman. Since the fields in question are not used this PR drops them.
> EDM-655: applications: reduce scope of events api

- docs/user/getting-started.md
IMO ideally we should make the documentation here the same as what's in `building-images.md` in this [section](https://github.com/flightctl/flightctl/blob/main/docs/user/building-images.md#building-the-os-image-bootc) as they are describing the same command, i.e.
```
$ OCI_REGISTRY=quay.io
$ OCI_IMAGE_REPO=${OCI_REGISTRY}/your_org/centos-bootc-flightctl
$ OCI_IMAGE_TAG=v1
$ sudo podman build -t ${OCI_IMAGE_REPO}:${OCI_IMAGE_TAG} .
```
...but I didn't try to do this here in case it introduces too much complexity in the getting started doc.
> EDM-412: Fix podman build typo

- pkg/ignition/ignition_wrapper.go
This PR fixed a bug where if a user name (string) was declared the ignition user.id was incorrectly always 0. Now it populates with the correct user.name.
```yaml
spec:
config:
- inline:
- content: this file is for "root" user
path: /tmp/file-for-root
- content: this file is for "user" user
group: user
path: /tmp/file-for-user
user: user
name: inline-files
```
```sh
$ ls -l /tmp/file-for-user 
-rw-r--r--. 1 root root 28 Oct 31 18:41 /tmp/file-for-user
```
```sh
$ ls -l /tmp/file-for-user 
-rw-r--r--. 1 user user 28 Oct 31 19:01 /tmp/file-for-user
```
> EDM-617: ignition: user,group ensure parse int

- internal/agent/device/bootstrap.go
We use NOTIFY_SOCKET to signal systemd that the service is ready. The problem is subprocess's which are invoked using os.exec consume the env and attempt to use the socket. This results in systemd spamming the logged complaint.
```
Nov 03 20:45:38 localhost.localdomain systemd[1]: flightctl-agent.service: Got notification message from PID 1281, but reception only permitted for main PID 817
```
This PR ensures that after successful bootstrap that the env is unset as it is no longer needed.
> NO-ISSUE: device/bootstrap: unset NOTIFY_SOCKET after bootstrap

- deploy/helm/flightctl/charts/keycloak/templates/keycloak-db-pvc.yaml
Fixes:
```
➜  staging helm upgrade --install --version=0.3.0-rc2 --namespace flightctl--runtime-ext flightctl oci://quay.io/flightctl/charts/flightctl --values values.yaml
Release "flightctl" does not exist. Installing it now.
Pulled: quay.io/flightctl/charts/flightctl:0.3.0-rc2
Digest: sha256:651c45c913b24c93fb0ad0639f5ece861a744a8f8d1b05e029c065be71d111a3
Error: YAML parse error on flightctl/charts/keycloak/templates/keycloak-db-pvc.yaml: error converting YAML to JSON: yaml: line 11: mapping values are not allowed in this context
```
> NO-ISSUE: Fix keycloak-db-pvc.yaml label indent

- deploy/deploy.mk
- test/test.mk
Without the deploy-e2e-extras the local registry won't be deployed on Kind, so agent-vm scripts will fail.
> EDM-622: Fix local registry deploy targets

- .packit.yaml
- hack/build_rpms.sh
- packaging/rpm/flightctl.spec
- test/README.md
- test/scripts/agent-images/Containerfile-e2e-base.local
- test/scripts/agent-images/README.md
- test/scripts/agent-images/create_agent_images.sh
- test/scripts/functions
- test/scripts/prepare_cli.sh
- test/test.mk
Enables:
* testing of specific rpm builds via the `FLIGHTCTL_RPM` environment variable,
* the build of epel-9 as that is the repository pulled from the centos9 stream image.
In addition removes the "v" prefix from rpm builds, which is not standard via packit config change.
> EDM-620: enable using specific rpm releases in e2e testing

- test/e2e/agent/agent_suite_test.go
- test/e2e/agent/agent_test.go
- test/e2e/agent/agent_updates_test.go
- test/harness/e2e/harness.go
This adds an additional E2E tests and some harness functions to help:
* Update devices
* Wait for devices status to be updated
> NO-ISSUE: Starting tests for the update lifecycle

- internal/agent/agent.go
- internal/agent/device/applications/applications.go
- internal/agent/device/applications/controller.go
- internal/agent/device/applications/lifecycle/compose.go
- internal/agent/device/applications/manager.go
- internal/agent/device/applications/mock_applications.go
- internal/agent/device/applications/podman_monitor.go
- internal/agent/device/applications/podman_monitor_test.go
- internal/agent/device/device.go
- internal/agent/device/fileio/fileio.go
- internal/agent/device/fileio/mock_fileio.go
- internal/agent/device/fileio/reader.go
- internal/agent/device/hook/manager.go
- internal/agent/shutdown/shutdown.go
- test/scripts/agent-images/Containerfile-e2e-v3.local
- test/scripts/agent-images/Containerfile-e2e-v4.local
- test/scripts/agent-images/create_agent_images.sh
- test/scripts/agent-images/test-podman-compose-sleep.yaml
This PR adds embedded compose application support.
Embeded applications are expected to be written to a sub directory of `/usr/local/etc/compose/manifests` where the sub directory is the application's name.
```
/usr/local/etc/compose/manifests/embedded-demo-app/podman-compose.yaml
```
The agent will start the application in the same way it handles image based applications and will also report its status. Below is an embedded application `embedded-demo-app` along side a declared OCI image-based application `compose-oci-example` in status.
```
bin/flightctl get devices/aupiu13663re92hg9q61cajan83gjp8e6tubpa01ncq9a0kgu6eg -o json | jq .status.applications
[
{
"name": "embedded-demo-app",
"ready": "3/3",
"restarts": 0,
"status": "Running"
},
{
"name": "compose-oci-example",
"ready": "3/3", …
```
> EDM-632: device/applications: add embedded compose support

- internal/agent/device/console/console_test.go
Console tests are running an interactive shell that appears to be breaking local unit tests. This PR makes the exec command a simple echo.
> NO-ISSUE: console: simplify exec test case

- pkg/k8s/selector/fields/lexer.go
- pkg/k8s/selector/fields/lexer_test.go
- pkg/k8s/selector/fields/selector_test.go
- Resolved an issue where the lexer state was incorrectly handled for nested selectors using 'exists' and 'notexists' tokens.
- Adjusted state transitions to ensure proper parsing of nested expressions.
- Added test cases to validate behavior with complex selector scenarios.
> EDM-423: Fix lexer state for nested exists/notexists selectors

- cmd/devicesimulator/main.go
Logger verbosity level may be supplied via -v flag
It may be one of "fatal", "error", "warn", "warning", "info", "debug"
Default: "debug"
> EDM-695: Logger verbosity flag was added (-v)

- test/e2e/agent/agent_suite_test.go
- test/e2e/agent/agent_test.go
- test/e2e/agent/agent_updates_test.go
- test/harness/e2e/harness.go
Adding agent status reporting test case: 75991. The tests are passing in both local and in ocp with vagrant env.
It verifies that flightctl-agent applies (or not) a configuration change to the device, and that the related status is correctly reported in the flightctl resource.
> EDM-704: Automate of Polarion test case 75991 - A flightctl resource status is reported

- internal/cli/get.go
- internal/service/device.go
We initially decided that summaryOnly, when listing devices, would raise an error if the end-user attempted to use flags such as limit and continue for pagination. The logic behind this decision was that summaryOnly does not return a list of devices, so pagination is not applicable.
However, field selectors, such as metadata.owner and others, should be usable with summaryOnly. Even when applying a status filter inside the field-selector query, there is no reason to disallow filtering by it.
> EDM-681: Allow field selector when 'summaryOnly' is enabled

- internal/tasks/config_storage.go
- internal/tasks/device_render.go
- internal/tasks/git_helpers.go
- pkg/ignition/ignition_wrapper.go
The device render task currently clones git repos for each device, which is inefficient for FC and can DoS the git server.  This commit caches the git data in valkey.  It is stored in ignition format, with a key per hash and path.
> EDM-708: Reduce git access

- internal/agent/device/errors/errors.go
- internal/agent/device/fileio/managed_file.go
- internal/agent/device/fileio/managed_file_test.go
This PR fixes a bug where managed files did not consider mode or user and group changes. The result was an ignition file that maintains the same content but different perms would not update on disk
> EDM-659: agent/fileio: ensure ignition gid, uid and mode

- internal/agent/device/status/status.go
if a transient networking error occurred when trying to update status we will degrade the device. This PR changes this from a Degraded status to a warn log line.
```
summary:
info: 'failed to update device status: Put "https://agent-api.flightctl.edge-devices.net/api/v1/devices/a063e22i764jja1nurfcqlkqu101qios3nob5c3fqsas7er1j89g/status":
dial tcp: lookup agent-api.flightctl.edge-devices.net on 192.168.124.1:53: read
udp 192.168.124.58:37945->192.168.124.1:53: i/o timeout'
status: Degraded
```
> EDM-842: transient networking error should not mark agent degraded

- internal/crypto/cert.go
- internal/service/certificatesigningrequest.go
This PR adds a check that a CSR with a specific name does not already exist, and also clarifies the error message when an enrollment request cannot be auto-approved.
Additionally it removes two checks which seem extraneous (but let me know if we do need these):
- checking that the CN for an enrollment certificate is 16 chars long (AFAIU this name is allowed to be anything)
- ~~checking that the `Name` for a CSR resource is valid in kubernetes (AFAIU this name is allowed to be anything)~~
> EDM-649: Improve checks and error message for enrollment CSRs

- api/v1alpha1/constructors.go
- api/v1alpha1/properties.go
- internal/agent/device/device.go
- internal/agent/device/errors/errors.go
- internal/service/agent/handler.go
- internal/service/common/device.go
- internal/service/device.go
- internal/service/device_test.go
- internal/tasks/device_disconnected.go
- test/e2e/agent/agent_test.go
- test/e2e/agent/agent_updates_test.go
- test/harness/e2e/harness.go
This PR implement the service-side logic for updating the device summary status, device update status, and application summary status based on the information provided by the agent and information only available service-side.
Depends on PR #675 (which centralizes API consts to break import cycles).
User documentation is in PR #637.
> EDM-417: Compute service-side statuses

- docs/user/README.md
- docs/user/device-api-statuses.md
Documents the Device API's `device.status.summay`, `device.status.updated`, and`device.status.applicationsSummary` statuses from the p.o.v. of the service.
Defines possible status values, their meaning and formal definitions. Also adds a state chart for the observable transitions between statuses and states.
Depends on implementation in PR #668.
> EDM-760: Document device statuses

- Makefile
- deploy/deploy.mk
- test/scripts/redeploy.sh
This commit introduces a few targets to help with re-deployment of api/worker/periodic services on development, avoiding the need to re-deploy the kind cluster in full.
> NO-ISSUE: redeploy kind pods for development

- deploy/helm/flightctl/templates/flightctl-db-config.yaml
- deploy/helm/flightctl/templates/flightctl-db-deployment.yaml
- Added `enable-extensions.sh` script to initialize PostgreSQL with specified extensions.
- The script checks the `POSTGRESQL_EXTENSIONS` environment variable and enables each extension dynamically.
- Integrated the script into the `flightctl-db` ConfigMap and Deployment.
> EDM-788: Add init script for PostgreSQL to set master user as superuser

- deploy/helm/flightctl/charts/ui/templates/flightctl-ui-route.yaml
The template helper was renamed [here](https://github.com/flightctl/flightctl/pull/641/files#diff-0bd34c1193202c7f6d02e308bc8015a9ca54f331bd0262752d7b803874b79525R23) as the template was moved from the UI repo to flightcl main repo.
> EDM-876 Fix helm template error

- deploy/helm/flightctl/templates/flightctl-api-deployment.yaml
This PR reverts the addition of a host mount on tzdata. tzdata is used by the API server to validate time zones. But this approach breaks in OCP as the pod does not have proper permissions.
> EDM-848: revert tzdata host mount

- .spelling
- docs/user/managing-devices.md
- docs/user/registering-microshift-devices-acm.md
This PR updates the "Auto-Registering Devices with MicroShift into ACM" section of the documentation to align it with the updated Device Lifecycle Hooks API and remove a number of implementation details that go beyond what would be expected from a user documentation.
The PR also removes a stray section from the Hooks API description.
> EDM-838: Update ACM registration doc

- cmd/flightctl-api/main.go
- go.mod
- go.sum
- internal/api_server/agentserver/grpc.go
- internal/api_server/server.go
- internal/console/console.go
- internal/service/console.go
- internal/service/handler.go
- test/util/util.go
1. This is keeping  the gRPC <-> gRPC transport for the console until UI migrates to websocket,
to avoid any release issues.
2. for the reason in (1) and to prove I am not breaking it, I am not doing the flightctl console ....  cmdline change in the same PR
3. This still continues to use the same annotation mechanisms, single console at once
but it's preparing for a few things:
a) Doing multiple consoles eventually, I create a ConsoleManager class
b) Moving from in-process channels for console comm (tx/rx), to distributed (through two queues per connection in redis/valkey)
that last thing would allow for horizontally scaling flightctl-api (or eventually splitting out the agent service) without breaking the console
can be tested with:
```
$ podman run --net=host --rm -ti …
```
> Console on websocket

- packaging/must-gather/flightctl-must-gather
This assists users in debug. Although the agent prints the version in the logs this makes it easier to find.
> NO-ISSUE: packaging: add flightctl agent version to must-gather

- .github/actions/setup-dependencies/action.yaml
- .github/workflows/integration-tests.yaml
- .github/workflows/lint-docs.yaml
- .github/workflows/lint.yaml
- .github/workflows/ppa-build.yaml
- .github/workflows/pr-e2e-testing.yaml
- .github/workflows/pr-smoke-testing.yaml
- .github/workflows/publish-cli-bins.yaml
- .github/workflows/publish-containers.yaml
- .github/workflows/unit-tests.yaml
We're currently using `ubuntu-latest` as GH runners, which currently still links to 22.04, but will soon automatically update to 24.04. See: https://github.com/actions/runner-images/issues/10636
This PR makes the switch now and pins the version to 24.04. As 24.04 comes with Podman 4.9, we can also remove the separate installation from SuSE repos.
> NO-ISSUE: Update GH runner

- internal/container/container.go
- internal/container/container_test.go
This PR reduces the scope of the bootc API to barebones to reduce surface area of breakage and only uses the types we explicitly use.
> EDM-966: reduce scope of bootc API

- Makefile
add `generate-proto` which will be used much less frequently and omit api/grpc from `generate`
> NO-ISSUE: omit grpc from make generate

- deploy/helm/flightctl/templates/flightctl-db-deployment.yaml
- deploy/helm/flightctl/values.yaml
- test/scripts/deploy_with_helm.sh
Allow setting an alternate image via variables to "make deploy".  For example:
IMAGE_PULL_SECRET_PATH="/path/to/pull/secret.yaml" SQL_IMAGE="registry.redhat.io/rhel8/postgresql-12" SQL_VERSION="1-181"
> EDM-953: Use approved Postgres

- .github/workflows/publish-containers.yaml
Ensure version metadata (`SOURCE_GIT_TAG`, `SOURCE_GIT_TREE_STATE`, `SOURCE_GIT_COMMIT`) is correctly passed during the build process.
> [release-0.5] EDM-1202: Fix missing Flightctl API Server version in upstream images

- packaging/selinux/flightctl_agent.te
This is a manual backport of #1162 
This reverts commit b8ae5f0496e1eae5ace104bcbae5027cf2f61b7b.
> Revert "EDM-1184: changed SELinux policy to allow systemd to start the service

- Containerfile.db-setup
Added the io.openshift.tags label to the db-setup container image.
This is required because the image is based on ubi9/ubi (not micro) and fails Conforma policy checks without the label.
The same was also applied to the cli-artifacts container image.
> NO-ISSUE: Add io.openshift.tags to db-setup container

- internal/service/common/device.go
- internal/service/event_handler_test.go
- internal/store/device.go
See #1482 for the full details
Fixes a panic that can occur in extreme circumstances in Device UpdateStatus events.
> EDM-1958: Fix Device UpdateStatus event panics
