cmd/devicesimulator/main.go, cmd/flightctl-agent/main.go, internal/agent/agent.go, internal/agent/enrollment.go
This probably needs some rework, but while I am away the following days feel free to merge and modify as necessary.
=> Basic agent support

cmd/flightctl/main.go, internal/service/device.go, internal/service/enrollmentrequest.go, internal/service/fleet.go, internal/store/device.go, internal/store/enrollmentrequest.go, internal/store/fleet.go, internal/store/labels.go, internal/store/model/device.go, internal/store/model/enrollmentrequest.go, internal/store/model/fleet.go, internal/store/model/resource.go
implements the labelSelector GET parameter and DB
storage layer.
current status: service/DB implemented, but looking at the cmdline tool changes for testing.
Resolves #17
=> Label selector for listing resources

cmd/flightctl/main.go, go.mod, go.sum
```
$ ./bin/flightctl get fleets
NAME
default
$ ./bin/flightctl get devices
NAME
75e85764af61c54a7df04a1740241ee2e764ee7ef975ae6316830d697426a908
89016cb25f18d3b4da9255bc2fbf9f934d44a709f9deaa1f148901c062aa3cd0
$ ./bin/flightctl get enrollmentrequests
NAME                                                                 APPROVED     REGION
75e85764af61c54a7df04a1740241ee2e764ee7ef975ae6316830d697426a908     true         default
89016cb25f18d3b4da9255bc2fbf9f934d44a709f9deaa1f148901c062aa3cd0     true         default
b0c9b755704cb13a57e62db96d3ca3899a5b17e233dba49b1024c61542991b93                  
```
Resolves #39
=> Tabular cli output

api/v1alpha1/openapi.yaml, api/v1alpha1/types.gen.go, cmd/flightctl-server/main.go, cmd/flightctl/main.go, internal/client/client.gen.go, internal/monitors/repotester/repotester.go, internal/server/server.gen.go, internal/service/repository.go, internal/store/model/repository.go, internal/store/repository.go, pkg/reqid/reqid.go, pkg/thread/thread.go
Thread that periodically tests the connectivity to a git repository and
updates the status of the corresponding repository resource accordingly.
=> Repository tester thread

internal/monitors/repotester/repotester.go, internal/monitors/repotester/repotester_test.go
=> Update repository available transition time only upon change

cmd/flightctl-server/main.go, internal/server/server.go
Unfortunately, it seems I had a bad rebase and introduced a bug as part of #74. Apologies.
This PR returns the original ordering of events and resolves the missing CA to the NewServiceHandler.
=> internal/server: ensure CA passed to handler

pkg/reqid/reqid.go
This PR fixes a race condition in reqid which is currently not thread safe. I found this using the -race detector as part of new tests added via #93
=> NO-ISSUE:  pkg: fix race on reqid

.github/dependabot.yml
package ecosystems:
- gomod: for golang dependencies
- github-actions: for github actions
=> MGMT-16711: Adding dependabot for daily scans

internal/tasks/resourcesync.go
This PR resolves an issue where ResourceSync fleets were deleted when "skipping" sync due to no new commits/RS-generation.
The run loop was assuming all resources were "removed from repo"
=> Fix: ResourceSync task skip

.github/workflows/lint.yaml, Makefile, hack/check-commit-message.sh, hack/check-commits.sh
1. Ensure commit message is linked to an issue
2. Ensure that 'make generate' was run before committing
=> Validate commit message and generated code

hack/check-commit-message.sh
=> Fix GH issues in commit message, disallow bugzilla

cmd/flightctl/main.go, deploy/podman/config.yaml, internal/config/config.go
=> Fix client file endpoint

internal/agent/agent_test.go, test/harness/test_harness.go, test/util/util.go
This allows reusability of the test harness to provide an easy framework to write more mocked E2E tests.
=> MGMT-17100: Factor out agent/server/db/client test harness

internal/store/device.go
If Device resource is deleted, and its associated EnrollmentRequest persists, a re-enrollment process of the device won't be possible. This makes sure that enrollment requests are deleted with its device.
=> MGMT-17120: Delete device's associated EnrollmentRequest

cmd/flightctl/main.go, internal/cli/apply.go, internal/cli/approve.go, internal/cli/delete.go, internal/cli/get.go, internal/util/util.go
Uses a common structure for options and how they are completed, validated, and run.
Cleans up description of commands and flags.
Adds support for JSON as output format for get command.
Depends on #136
=> Further CLI Improvements

internal/agent/agent.go, internal/agent/device/bootstrap.go, internal/agent/device/device.go, internal/agent/device/osimage.go, internal/agent/device/status/conditions.go, internal/agent/device/status/mock_status.go, internal/agent/device/status/status.go, internal/container/container.go
This PR adds the first iteration of the os image controller.
Followup: add bootstrap logic #180
=> MGMT-16600: os image controller

internal/agent/device/fileio/writer.go
This PR improves the performance of fileio  atomic writer directly instead of converting files to and from ignition.
=> NO-ISSUE: improve fileio writer

cmd/flightctl-agent/main.go, cmd/flightctl-server/main.go, internal/agent/config.go, internal/agent/config_test.go, internal/config/config.go
=> NO-ISSUE: Agent and server log level defined in config

internal/agent/device/config/controller.go, internal/agent/device/device.go, internal/agent/device/osimage.go, internal/agent/device/spec/spec.go, internal/agent/device/status/status.go, internal/util/util.go
This PR cleans up the unnecessary use of klog and does other minor cleanups
=> NO-ISSUE: minor code and log cleanup

internal/agent/device/status/containers.go, internal/agent/device/status/containers_test.go
It also fixes the Condition status, which was not carrying over the count of notRunning containers among podman and crio engines.
=> NO-ISSUE: Add missing test for both podman and crio containers

go.mod, go.sum, pkg/queues/amqp_provider.go, pkg/queues/provider.go
Add AMQP queues infrastrcture to pkg.
It includes simplified interface for consuming and producing queues payload
/cc @hexfusion
=> MGMT-18183: Add AMQP queues infrastructure

README.md
Replacing config.yaml with client.yaml
=> NO-ISSUE: Fix readme client config file name

README.md
Remove section about running server locally as it does not work anymore
=> NO-ISSUE: Update readme to include login command.

internal/cli/get.go
Currently the CLI always prints singular items as YAML. Now, the default is tabular format regardless of single/multiple items.  YAML and JSON formats can be passed for both cases as well.
=> EDM-184: CLI should respect output format

internal/flterrors/flterrors.go, internal/service/device.go, internal/store/common.go, internal/store/device.go, internal/store/model/device.go, internal/store/model/resource.go, internal/tasks/device_disconnected_test.go, test/integration/store/device_test.go
Compare resource version when performing device updates.  In case of
conflict perform retry when applicable.
=>     MGMT-18287: Compare resourceVersions when updating a resource     

internal/flterrors/flterrors.go, internal/service/common/enrollmentrequest.go, internal/service/enrollmentrequest.go, internal/store/common.go, internal/store/device.go, internal/store/enrollmentrequest.go, internal/store/fleet.go, internal/store/model/enrollmentrequest.go, internal/store/model/fleet.go, test/integration/store/fleet_test.go
Changes for enrollmentrequests and fleets.
=> MGMT-18287: Compare resourceVersions when updating a resource

examples/templateversion.yaml
Removing templateversion example
=> NO-ISSUE: remove templateversion example

internal/tasks/device_disconnected.go
According to the Data Dictionary Definition, the info message for the "Unknown" UpdatedStatus should be "Did not check in for more than X minutes"
=> NO-ISSUE: Change Unknown UpdatedStatus text

deploy/deploy.mk, internal/cli/console.go, test/README.md, test/e2e/agent/agent_test.go, test/e2e/cli/cli_test.go, test/harness/e2e/harness.go, test/harness/e2e/vm/vm_linux.go, test/test.mk, test/util/ip.go
This PR introduces a testing framework for the CLI tool, and
adds some basic examples for CLI testing.
One of the tests is about basic testing for the console, as part
of writing the tests some bugs were found and fixed:
* Correct exit handing with 3 x CTRL-B
* Avoid several panics on stdin or stdout closed unexpectedly
=> E2E testing for the cli tool + fix console bugs

README.md
Even with 'openssl-devel' installed, I recieved an error while trying to run 'make e2e-tests". This was solved by installing 'openssl'
=> Missing prequisite package 'openssl'

README.md
See title. I was not able to `make deploy` until I changed to this for mockgen. Thanks @hexfusion for unblocking me on this last week.
=> NO-ISSUE: Update mockgen requirement in README

internal/api_server/agentserver/grpc.go, internal/api_server/middleware/auth.go, internal/api_server/middleware/tls.go
Followup for https://github.com/flightctl/flightctl/pull/430
=> NO-ISSUE: Move grpc auth logic to middleware package

.spelling, Makefile, docs/user/README.md, docs/user/getting-started.md
This is an initial "getting started" section. It's about showing a very basic, highly opinionated way how to deploy the service and CLI and get a device into FC.
Note the provided shell commands need verification and missing outputs need to be added still.
=> MGMT-17670: Add getting started doc

internal/service/fleet.go, internal/store/fleet.go, internal/store/model/fleet.go, internal/store/model/resource.go, test/integration/store/fleet_test.go, test/util/create_utils.go
Add the total devices also for Get operation even if WithSummary is not set.
=> EDM-280:  Add total devices per fleet for List operation

README.md
Small README fixes: updated default VM user and password, and VM cleaning cmd.
=> NO-ISSUE: small readme fixes

internal/crypto/cert.go, internal/crypto/csr.go, internal/service/certificatesigningrequest.go, internal/service/enrollmentrequest.go
Note: I'll drop the first 3 commits when #453 is merged.
=> MGMT-18558: Issue certificate when CSR is approved

internal/service/certificatesigningrequest.go, internal/service/device.go, internal/service/enrollmentrequest.go, internal/service/fleet.go, internal/service/repository.go, internal/service/resourcesync.go
Added also handling of flterrors.ErrResourceVersionConflict
=> EDM-287: 500 when trying to apply a device yaml without removing the creationTimestamp and resourceVersion

.github/workflows/pr-smoke-testing.yaml, cmd/devicesimulator/main.go, internal/agent/device/bootstrap.go, internal/client/config.go, test/harness/e2e/harness.go, test/util/util.go
1. Fixing simutalor configuration and pathes
2. Fixing small code issues
3. Adding auto approve for devices that were created by simulator
=> NO-ISSUE: Fix simulator

.spelling, docs/user/getting-started.md
depends on: https://github.com/flightctl/flightctl/pull/481 
Otherwise the documentation won't work
=> EDM-298: Write documentation for deployment with keycloak

internal/agent/device/fileio/managed_file.go, internal/agent/device/fileio/managed_file_test.go
=> EDM-288: Adding isDir validation to file path provided by ignition

internal/cli/get.go
EDM-388: cli will set valid to false in case overlapping condition will be set to true
=> EDM-388: cli will set valid to false in case overlapping condition will be set to true

internal/agent/device/config/controller.go
EDM-288: Improve error message in case we fail to apply ignition to device
=> EDM-288: Improve error message in case we fail to apply ignition to device

internal/agent/device/hook/actions.go, internal/agent/device/hook/default_hooks.go, internal/agent/device/hook/manager.go
If there is an attempt to remove a compose file twice, running the hook the second time may fail since the compose file does not exist. This commit checks in case there is a failure to run the podman-compose down, if the compose file does not exist and there is no container that was launched by the compose file.
In additon, it clears degraded status for hooks, if a file a hook for a failed file has been recovered.
=> EDM-398: A device becomes degraded after a compose file is removed

deploy/deploy.mk, test/scripts/agent-images/prepare_agent_config.sh, test/scripts/get_endpoints.sh
This will be used from E2E tests to target either a real cluster or a kind based cluster.
=> EDM-511: Provide script to generate endpoint environment variables

.github/workflows/pr-smoke-testing.yaml, deploy/helm/flightctl/values.kind.yaml, internal/client/config.go, test/scripts/deploy_with_helm.sh
This actually depends on #529 , rebase once that one merges.
=> NO-ISSUE: Cleanup helm install details

docs/user/building-images.md, internal/cli/certificate.go, internal/cli/csrconfig.go
=> EDM-595: Bug fixes for CLI cmd description errors

internal/api_server/agentserver/server.go
When Prometheus is disabled, agentserver.metrics == nil. This will cause a segmentation fault if metrics.AgentServerMiddleware is called, so make the usage of that middleware dependent on if metrics were initialized.
=> NO-ISSUE: Fix nil pointer deref in agentserver when metrics == nil

docs/user/building-images.md
This link was giving a 404 error.
=> NO ISSUE: fix link typo

deploy/helm/flightctl/Chart.lock, deploy/helm/flightctl/Chart.yaml
=> NO-ISSUE: Update UI to v0.3.0

docs/developer/architecture/field-selectors.md, docs/user/field-selectors.md
This PR introduces developer documentation for the field-selector implementation.
I was asked to create this documentation and would greatly appreciate your feedback.
=> Add developer documentation for field-selector

.spelling, docs/user/registering-microshift-devices-acm.md
1. ca.crt in repository
2. verificationSuffix in repository (EDM-648)
3. pull-secret in fleet spec
=> EDM-621: Fix microshift registration docs

test/test.mk
Adding prepare-e2e-test command to separate the e2e test preparation from the test running
=> NO-ISSUE: add command to prepare e2e test

.spelling, docs/user/managing-devices.md
=> EDM-761: Document updated Hooks API

.github/actions/setup-dependencies/action.yaml
This avoids issues with linting
=> NO-ISSUE: libvirt-dev should always be installed

docs/developer/enhancements/fep-000-api-device-fleet.md, docs/user/managing-devices.md, docs/user/managing-fleets.md, docs/user/registering-microshift-devices-acm.md
=> NO-ISSUE: Add API group to docs yamls

docs/user/auth-resources.md, docs/user/managing-devices.md, docs/user/troubleshooting.md, internal/cli/get.go
bp of https://github.com/flightctl/flightctl/pull/913
=> [release-0.5] EDM-1168: Make --rendered flag return the full device

docs/developer/architecture/field-selectors.md, docs/user/field-selectors.md, internal/store/model/selectors.go
Corrected inconsistent casing in field selector names to maintain uniform camelCase formatting.
=> [release-0.5]  EDM-1181: ensure camelCase consistency in selector names

.spelling, docs/user/disconnected-cluster.md
bp of https://github.com/flightctl/flightctl/pull/930
=> [release-0.5] EDM-1076: Improve docs for installing fctl on disconnected env

docs/user/building-images.md, docs/user/managing-devices.md, internal/agent/agent.go, internal/agent/client/client.go, internal/agent/client/podman.go, internal/agent/device/applications/controller_test.go, internal/agent/device/applications/podman_monitor_test.go, internal/agent/device/device_test.go, internal/agent/device/os/os.go
=> [release-0.5] EDM-1191: docs/managing-devices: add section on pull secrets

internal/cli/console.go
=> Modify console 0.7

.spelling, docs/user/configuring-agent.md, docs/user/managing-devices.md
This is a manual backport of #1145
=> EDM-1437: document viewing and customizing the device system info

.spelling, docs/user/README.md, docs/user/managing-devices.md
This is a manual cherry-pick of #1147
=> EDM-1201: document device update policy

internal/agent/agent.go, internal/agent/device/applications/manager.go, internal/agent/device/applications/podman_monitor.go, internal/agent/device/errors/errors.go, internal/agent/device/policy/manager.go, internal/agent/device/systeminfo/gpu.go, internal/agent/device/systeminfo/system_info.go
This is a manual backport of #1169
=> EDM-1344: agent: improve logging

internal/agent/client/compose.go, internal/agent/device/applications/applications.go, internal/agent/device/applications/lifecycle/compose.go, internal/agent/device/applications/lifecycle/compose_test.go, internal/agent/device/applications/lifecycle/lifecycle.go, internal/agent/device/applications/manager_test.go, internal/agent/device/applications/mock_applications.go, internal/agent/device/applications/podman_monitor.go, internal/agent/device/applications/podman_monitor_test.go, internal/agent/device/applications/provider/embedded.go, internal/agent/device/applications/provider/image.go, internal/agent/device/applications/provider/inline.go, internal/agent/device/applications/provider/provider.go, internal/agent/device/applications/provider/volume.go, internal/agent/device/applications/provider/volume_test.go
This is a manual cherry-pick of #1270
=> EDM-1740: agent/applications: add image reference to volume status

deploy/podman/flightctl-api/flightctl-api-config/config.yaml.template, deploy/podman/flightctl-api/flightctl-api-config/init.sh, deploy/podman/flightctl-ui/flightctl-ui-config/init.sh, deploy/podman/service-config.yaml
Backport of https://github.com/flightctl/flightctl/pull/1320
=> EDM-1807: Enable OIDC option for quadlets deployment

deploy/helm/flightctl/templates/flightctl-cleanup-job.yaml, deploy/helm/flightctl/values.yaml
Since the commit https://github.com/flightctl/flightctl/commit/1a21ea8e7b73dc2c0945d856758e5f195c6add68 had caused this [bug](https://issues.redhat.com/browse/EDM-1935)
I'm reverting it . I'll contact Shaun (who opened the og problem) and together we will think of a solution.
=> NO-ISSUE: reverting EDM-1871

docs/developer/README.md, docs/user/managing-devices.md, internal/cli/get.go, internal/cli/get_test.go, internal/cli/helpers.go, internal/cli/resume.go, test/e2e/cli/cli_events_test.go
(cherry picked from commit 5682e9832bf3091d17bb0114a0915a5e0ca69006)
=> EDM-552: support for cli format

deploy/helm/flightctl/README.md, deploy/helm/flightctl/README.md.gotmpl, deploy/helm/flightctl/templates/_helpers.tpl, deploy/helm/flightctl/templates/flightctl-alert-exporter-deployment.yaml, docs/user/external-database.md
EDM-2228: Installation fails when using an external database with sslmode verify-ca
=> EDM-2228: Cherry pick 1716 to v0.10

internal/agent/device/lifecycle/manager.go, internal/store/gorm.go
=> EDM-2271: Fix TPM Activate Credential with tracing disabled

internal/agent/device/dependency/dependency.go, internal/agent/device/dependency/dependency_test.go
This is a manual cherry-pick of #1766
=> EDM-2273: device/dependency: ensure stale images are removed on version change
